CREATE DATABASE QLY_SANPHAM
GO 

USE QLY_SANPHAM
GO

CREATE TABLE SANPHAM(
	MASP VARCHAR(6) PRIMARY KEY,
	TENSP NVARCHAR(255),
	GIATIEN MONEY,
	SL INT,
	GHICHU NVARCHAR(255) NOT NULL DEFAULT(N'Không có ghi chú')
);

CREATE TABLE HOADON(
	MAHD VARCHAR(11) PRIMARY KEY,
	TENKH NVARCHAR(255),
	SL INT,
	THOIGIAN DATETIME,
	HINHTHUC NVARCHAR(50)
);

CREATE TABLE CTHD(
	MAHD VARCHAR(11), 
    MASP VARCHAR(6), 
    TENKH NVARCHAR(255), 
    GIATIEN MONEY NOT NULL, 
    SL INT NOT NULL,
    HINHTHUC NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MAHD, MASP),
    CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CTHD_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

SELECT * FROM HOADON
SELECT * FROM CTHD
SELECT * FROM SANPHAM